interface TeamMember {
  id: string;
  name: string;
  role: string;
  email: string;
  linkedIn?: string;
  github?: string;
  slack?: string;
  calendarAvailability?: string;
  avatar: string;
  skills: string[];
}

interface Department {
  id: string;
  name: string;
  color: string;
  icon: string;
  lead: TeamMember;
  teamSize: number;
}

export const departments: Department[] = [
  {
    id: 'ai-ml-platform',
    name: 'AI/ML Platform Services',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-800',
    icon: '🤖',
    teamSize: 18,
    lead: {
      id: 'lead-ai-ml',
      name: 'Dr. Rachel Singh',
      role: 'Head of AI/ML Platform',
      email: 'rachel.singh@pivot.com',
      linkedIn: 'https://linkedin.com/in/rachelsingh',
      github: 'https://github.com/rachelsingh',
      slack: 'https://pivot.slack.com/team/UAIML001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/rachel-singh',
      avatar: '👩‍🔬',
      skills: ['Machine Learning', 'AI Platform Architecture', 'MLOps', 'Deep Learning'],
    },
  },
  {
    id: 'accounting',
    name: 'Accounting',
    color: 'bg-emerald-100 border-emerald-300 text-emerald-800',
    icon: '💰',
    teamSize: 12,
    lead: {
      id: 'lead-accounting',
      name: 'Patricia Wong',
      role: 'VP of Accounting',
      email: 'patricia.wong@pivot.com',
      linkedIn: 'https://linkedin.com/in/patriciawong',
      slack: 'https://pivot.slack.com/team/UACCT001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/patricia-wong',
      avatar: '👩‍💼',
      skills: ['Financial Reporting', 'GAAP', 'Audit Management', 'Tax Compliance'],
    },
  },
  {
    id: 'asset-management',
    name: 'Asset Management',
    color: 'bg-amber-100 border-amber-300 text-amber-800',
    icon: '📦',
    teamSize: 8,
    lead: {
      id: 'lead-asset',
      name: 'Marcus Brown',
      role: 'Director of Asset Management',
      email: 'marcus.brown@pivot.com',
      linkedIn: 'https://linkedin.com/in/marcusbrown',
      slack: 'https://pivot.slack.com/team/UASST001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/marcus-brown',
      avatar: '👨‍💼',
      skills: ['Asset Tracking', 'Inventory Management', 'Lifecycle Planning', 'Cost Optimization'],
    },
  },
  {
    id: 'comms',
    name: 'Comms',
    color: 'bg-pink-100 border-pink-300 text-pink-800',
    icon: '📢',
    teamSize: 10,
    lead: {
      id: 'lead-comms',
      name: 'Jennifer Lee',
      role: 'VP of Communications',
      email: 'jennifer.lee@pivot.com',
      linkedIn: 'https://linkedin.com/in/jenniferlee',
      slack: 'https://pivot.slack.com/team/UCOMM001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/jennifer-lee',
      avatar: '👩‍💼',
      skills: ['Corporate Communications', 'PR Strategy', 'Internal Comms', 'Crisis Management'],
    },
  },
  {
    id: 'compute',
    name: 'Compute',
    color: 'bg-cyan-100 border-cyan-300 text-cyan-800',
    icon: '⚡',
    teamSize: 22,
    lead: {
      id: 'lead-compute',
      name: 'Thomas Anderson',
      role: 'Head of Compute Infrastructure',
      email: 'thomas.anderson@pivot.com',
      linkedIn: 'https://linkedin.com/in/thomasanderson',
      github: 'https://github.com/thomasanderson',
      slack: 'https://pivot.slack.com/team/UCOMP001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/thomas-anderson',
      avatar: '👨‍💻',
      skills: ['Cloud Computing', 'HPC', 'Container Orchestration', 'Performance Optimization'],
    },
  },
  {
    id: 'customer-experience',
    name: 'Customer Experience',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    icon: '🌟',
    teamSize: 15,
    lead: {
      id: 'lead-cx',
      name: 'Sophia Martinez',
      role: 'VP of Customer Experience',
      email: 'sophia.martinez@pivot.com',
      linkedIn: 'https://linkedin.com/in/sophiamartinez',
      slack: 'https://pivot.slack.com/team/UCX001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/sophia-martinez',
      avatar: '👩‍💼',
      skills: ['CX Strategy', 'Journey Mapping', 'User Research', 'Customer Analytics'],
    },
  },
  {
    id: 'customer-support',
    name: 'Customer Support',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    icon: '🎧',
    teamSize: 35,
    lead: {
      id: 'lead-support',
      name: 'Daniel Park',
      role: 'VP of Customer Support',
      email: 'daniel.park@pivot.com',
      linkedIn: 'https://linkedin.com/in/danielpark',
      slack: 'https://pivot.slack.com/team/USUPP001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/daniel-park',
      avatar: '👨‍💼',
      skills: ['Support Operations', 'Team Leadership', 'Customer Success', 'SLA Management'],
    },
  },
  {
    id: 'data-center-ops',
    name: 'Data Center Operations',
    color: 'bg-slate-100 border-slate-300 text-slate-800',
    icon: '🖥️',
    teamSize: 28,
    lead: {
      id: 'lead-dc-ops',
      name: 'Robert Jackson',
      role: 'Director of Data Center Operations',
      email: 'robert.jackson@pivot.com',
      linkedIn: 'https://linkedin.com/in/robertjackson',
      slack: 'https://pivot.slack.com/team/UDCOP001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/robert-jackson',
      avatar: '👨‍🔧',
      skills: ['Data Center Management', 'Operations', '24/7 Monitoring', 'Incident Response'],
    },
  },
  {
    id: 'data-center-planning',
    name: 'Data Center Planning',
    color: 'bg-gray-100 border-gray-300 text-gray-800',
    icon: '📋',
    teamSize: 12,
    lead: {
      id: 'lead-dc-plan',
      name: 'Karen White',
      role: 'Director of Data Center Planning',
      email: 'karen.white@pivot.com',
      linkedIn: 'https://linkedin.com/in/karenwhite',
      slack: 'https://pivot.slack.com/team/UDCPL001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/karen-white',
      avatar: '👩‍💼',
      skills: ['Capacity Planning', 'Infrastructure Design', 'Strategic Planning', 'Cost Modeling'],
    },
  },
  {
    id: 'demand-gen',
    name: 'Demand Gen',
    color: 'bg-rose-100 border-rose-300 text-rose-800',
    icon: '🎯',
    teamSize: 14,
    lead: {
      id: 'lead-demand',
      name: 'Amanda Collins',
      role: 'VP of Demand Generation',
      email: 'amanda.collins@pivot.com',
      linkedIn: 'https://linkedin.com/in/amandacollins',
      slack: 'https://pivot.slack.com/team/UDMND001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/amanda-collins',
      avatar: '👩‍💼',
      skills: ['Lead Generation', 'Marketing Automation', 'Campaign Management', 'Analytics'],
    },
  },
  {
    id: 'eng-ops',
    name: 'Engineering Operations',
    color: 'bg-teal-100 border-teal-300 text-teal-800',
    icon: '⚙️',
    teamSize: 20,
    lead: {
      id: 'lead-eng-ops',
      name: 'Kevin Zhang',
      role: 'Director of Engineering Operations',
      email: 'kevin.zhang@pivot.com',
      linkedIn: 'https://linkedin.com/in/kevinzhang',
      github: 'https://github.com/kevinzhang',
      slack: 'https://pivot.slack.com/team/UENOP001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/kevin-zhang',
      avatar: '👨‍💻',
      skills: ['DevOps', 'CI/CD', 'Release Management', 'Tooling'],
    },
  },
  {
    id: 'facility-eng',
    name: 'Facility Engineering',
    color: 'bg-lime-100 border-lime-300 text-lime-800',
    icon: '🏗️',
    teamSize: 16,
    lead: {
      id: 'lead-facility',
      name: 'Richard Thompson',
      role: 'Head of Facility Engineering',
      email: 'richard.thompson@pivot.com',
      linkedIn: 'https://linkedin.com/in/richardthompson',
      slack: 'https://pivot.slack.com/team/UFACL001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/richard-thompson',
      avatar: '👨‍🔧',
      skills: ['HVAC Systems', 'Power Distribution', 'Building Management', 'Energy Efficiency'],
    },
  },
  {
    id: 'fleet',
    name: 'Fleet',
    color: 'bg-yellow-100 border-yellow-300 text-yellow-800',
    icon: '🚗',
    teamSize: 10,
    lead: {
      id: 'lead-fleet',
      name: 'Michelle Davis',
      role: 'Director of Fleet Management',
      email: 'michelle.davis@pivot.com',
      linkedIn: 'https://linkedin.com/in/michelledavis',
      slack: 'https://pivot.slack.com/team/UFLET001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/michelle-davis',
      avatar: '👩‍💼',
      skills: ['Fleet Operations', 'Vehicle Management', 'Logistics', 'Cost Control'],
    },
  },
  {
    id: 'it-biz-gtm',
    name: 'IT Business Platforms – GTM',
    color: 'bg-violet-100 border-violet-300 text-violet-800',
    icon: '💼',
    teamSize: 18,
    lead: {
      id: 'lead-it-gtm',
      name: 'Brian Wilson',
      role: 'Director of IT Business Platforms',
      email: 'brian.wilson@pivot.com',
      linkedIn: 'https://linkedin.com/in/brianwilson',
      slack: 'https://pivot.slack.com/team/UITGTM01',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/brian-wilson',
      avatar: '👨‍💻',
      skills: ['Salesforce', 'CRM Systems', 'Business Applications', 'GTM Tools'],
    },
  },
  {
    id: 'it-data-eng',
    name: 'IT Data Engineering',
    color: 'bg-green-100 border-green-300 text-green-800',
    icon: '📊',
    teamSize: 24,
    lead: {
      id: 'lead-it-data',
      name: 'Linda Chen',
      role: 'Head of IT Data Engineering',
      email: 'linda.chen@pivot.com',
      linkedIn: 'https://linkedin.com/in/lindachen',
      github: 'https://github.com/lindachen',
      slack: 'https://pivot.slack.com/team/UITDAT01',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/linda-chen',
      avatar: '👩‍💻',
      skills: ['Data Pipelines', 'ETL', 'Data Warehousing', 'Big Data'],
    },
  },
  {
    id: 'it-infra-eng',
    name: 'IT Infrastructure and Operations – Engineering',
    color: 'bg-blue-100 border-blue-300 text-blue-800',
    icon: '🔧',
    teamSize: 30,
    lead: {
      id: 'lead-it-infra-eng',
      name: 'Steven Martinez',
      role: 'VP of IT Infrastructure Engineering',
      email: 'steven.martinez@pivot.com',
      linkedIn: 'https://linkedin.com/in/stevenmartinez',
      github: 'https://github.com/stevenmartinez',
      slack: 'https://pivot.slack.com/team/UITIEN01',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/steven-martinez',
      avatar: '👨‍💻',
      skills: ['Infrastructure Engineering', 'Automation', 'System Design', 'Cloud Architecture'],
    },
  },
  {
    id: 'it-infra-support',
    name: 'IT Infrastructure and Operations – IT Support',
    color: 'bg-sky-100 border-sky-300 text-sky-800',
    icon: '🛠️',
    teamSize: 25,
    lead: {
      id: 'lead-it-support',
      name: 'Nancy Rodriguez',
      role: 'Director of IT Support',
      email: 'nancy.rodriguez@pivot.com',
      linkedIn: 'https://linkedin.com/in/nancyrodriguez',
      slack: 'https://pivot.slack.com/team/UITSP001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/nancy-rodriguez',
      avatar: '👩‍💻',
      skills: ['Help Desk', 'Technical Support', 'Service Management', 'ITIL'],
    },
  },
  {
    id: 'it-product-strategy',
    name: 'IT Product & Strategy',
    color: 'bg-fuchsia-100 border-fuchsia-300 text-fuchsia-800',
    icon: '🎯',
    teamSize: 14,
    lead: {
      id: 'lead-it-prod',
      name: 'Christopher Lee',
      role: 'VP of IT Product & Strategy',
      email: 'christopher.lee@pivot.com',
      linkedIn: 'https://linkedin.com/in/christopherlee',
      slack: 'https://pivot.slack.com/team/UITPRD01',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/christopher-lee',
      avatar: '👨‍💼',
      skills: ['IT Strategy', 'Product Management', 'Technology Roadmap', 'Vendor Management'],
    },
  },
  {
    id: 'it-software-eng',
    name: 'IT Software Engineering',
    color: 'bg-indigo-100 border-indigo-300 text-indigo-800',
    icon: '💻',
    teamSize: 40,
    lead: {
      id: 'lead-it-sw',
      name: 'Jessica Wang',
      role: 'VP of IT Software Engineering',
      email: 'jessica.wang@pivot.com',
      linkedIn: 'https://linkedin.com/in/jessicawang',
      github: 'https://github.com/jessicawang',
      slack: 'https://pivot.slack.com/team/UITSW001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/jessica-wang',
      avatar: '👩‍💻',
      skills: ['Software Development', 'Full Stack', 'Microservices', 'API Design'],
    },
  },
  {
    id: 'networking',
    name: 'Networking',
    color: 'bg-orange-100 border-orange-300 text-orange-800',
    icon: '🌐',
    teamSize: 22,
    lead: {
      id: 'lead-network',
      name: 'Michael Brown',
      role: 'Head of Networking',
      email: 'michael.brown@pivot.com',
      linkedIn: 'https://linkedin.com/in/michaelbrown',
      slack: 'https://pivot.slack.com/team/UNETW001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/michael-brown',
      avatar: '👨‍💻',
      skills: ['Network Architecture', 'SDN', 'BGP', 'Security'],
    },
  },
  {
    id: 'physical-security',
    name: 'Physical Security',
    color: 'bg-red-100 border-red-300 text-red-800',
    icon: '🔒',
    teamSize: 18,
    lead: {
      id: 'lead-phys-sec',
      name: 'David Miller',
      role: 'Director of Physical Security',
      email: 'david.miller@pivot.com',
      linkedIn: 'https://linkedin.com/in/davidmiller',
      slack: 'https://pivot.slack.com/team/UPHYS001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/david-miller',
      avatar: '👨‍✈️',
      skills: ['Access Control', 'Surveillance Systems', 'Risk Assessment', 'Compliance'],
    },
  },
  {
    id: 'product',
    name: 'Product',
    color: 'bg-purple-100 border-purple-300 text-purple-800',
    icon: '📱',
    teamSize: 28,
    lead: {
      id: 'lead-product',
      name: 'Sarah Johnson',
      role: 'VP of Product',
      email: 'sarah.johnson@pivot.com',
      linkedIn: 'https://linkedin.com/in/sarahjohnson',
      slack: 'https://pivot.slack.com/team/UPROD001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/sarah-johnson',
      avatar: '👩‍💼',
      skills: ['Product Strategy', 'Roadmap Planning', 'User Research', 'Analytics'],
    },
  },
  {
    id: 'product-marketing',
    name: 'Product Marketing',
    color: 'bg-pink-100 border-pink-300 text-pink-800',
    icon: '🚀',
    teamSize: 16,
    lead: {
      id: 'lead-prod-mkt',
      name: 'Emily Taylor',
      role: 'VP of Product Marketing',
      email: 'emily.taylor@pivot.com',
      linkedIn: 'https://linkedin.com/in/emilytaylor',
      slack: 'https://pivot.slack.com/team/UPMKT001',
      calendarAvailability: 'https://calendar.google.com/calendar/appointments/schedules/emily-taylor',
      avatar: '👩‍💼',
      skills: ['Go-to-Market', 'Product Positioning', 'Competitive Analysis', 'Launch Strategy'],
    },
  },
];

export type { Department, TeamMember };

